version: 2
jobs:
  workflow:
    machine: true
    working_directory: ~/gliderlabs/herokuish
    parallelism: 4
    steps:
      - checkout
      - run: |
          case $CIRCLE_NODE_INDEX in 0) make shellcheck;; esac
      - run: |
          case $CIRCLE_NODE_INDEX in 0) make lint;; esac
      - run: |
          make circleci
      - run: |
          make deps fpm package_cloud
      - run: |
          make build
      - run: |
          case $CIRCLE_NODE_INDEX in 0) basht tests/**/tests.sh ;; esac
      - run: |
          tests=$(circleci tests glob buildpacks/*/tests/*/test.sh | circleci tests split --split-by=timings | xargs)
          echo "executing tests: $tests"
          basht $tests
      - store_artifacts:
          path: build
          destination: build
      - deploy:
          name: release
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              export PACKAGECLOUD_REPOSITORY=dokku/dokku
              make release release-packagecloud
            fi
  release-workflow:
    machine: true
    working_directory: ~/gliderlabs/herokuish
    steps:
      - checkout
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run: |
          docker image build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG-18 -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest-18 --build-arg STACK_VERSION=18 .
      - run: |
          docker image build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG-20 -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest-20 --build-arg STACK_VERSION=20 .
      - run: |
          docker image push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG-18
          docker image push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest-18
      - run: |
          docker image push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG-20
          docker image push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest-20

workflows:
  version: 2
  workflow:
    jobs:
      - workflow
  release-workflow:
    jobs:
      - release-workflow:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
