version: 2
jobs:
  build:
    machine: true
    working_directory: ~/gliderlabs/herokuish
    parallelism: 1
    steps:
      - checkout
      - run: |
          case $CIRCLE_NODE_INDEX in 0) make shellcheck;; esac
      - run: |
          case $CIRCLE_NODE_INDEX in 0) make lint;; esac
      - run: |
          make circleci
      - run: |
          make deps
      - run: |
          make build
      - run: |
          case $CIRCLE_NODE_INDEX in 0) basht tests/**/tests.sh ;; esac
      - run: |
          tests=$(circleci tests glob buildpacks/*/tests/*/test.sh | circleci tests split --split-by=timings | xargs)
          echo "executing tests: $tests"
          basht $tests
      - deploy:
          name: release
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              make release
            fi
